PATCH http://localhost:5001/personaldetails/604e58a4dd84f60a4fb41aa8
Content-Type: application/json

{
    "jobTitle": "Senior Developer"
}

###

DELETE http://localhost:5001/personaldetails/604e58a4dd84f60a4fb41aa8


###

POST http://localhost:5001/personaldetails
Content-Type: application/json

{
    "cv": "604d6f3b4919d19f95f3200f",
    "jobTitle": "job title",
    "email": "jorge_pezzuol@hotmail.com",
    "firstName": "Jorge",
    "lastName": "Pezzuol"
}

###

GET http://localhost:5001/personaldetails/cv/604d6f3b4919d19f95f3200f

###

GET http://localhost:5001/personaldetails/604e58a4dd84f60a4fb41aa8

