GET http://localhost:5001/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDQyZGIxODZiOWI2YzJjMzc0ZDZlNzMiLCJlbWFpbCI6ImpvcmdlMkB0ZXN0LmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJG9MbmV4eTF6d2xsL3lNYnUzTzEvdS5qdGpYcG5sRFRRU0g3NWtadHF5UFJ2bW9zWkU3cjgyIiwiX192IjowLCJpYXQiOjE2MTUxNjgyODksImV4cCI6MTYxNTE2ODMxNH0.qTW5IThYrQfc8mhA395hrkgpyVZiVReCwMSJ4_vXlk0

###

POST http://localhost:5001/user
Content-Type: application/json

{
    "email": "jorge2@test.com",
    "password": "testpass"
}

###

POST http://localhost:5001/login
Content-Type: application/json

{
    "email":"jorge2@test.com",
    "password": "testpass"
}

###

PATCH http://localhost:5001/professionalsummary/604e53c9635db508b9216c35
Content-Type: application/json

{
    "cv": "604d6f3b4919d19f95f3200f",
    "description": "<p><strong>ggg</strong></p>"
}

###

DELETE http://localhost:5001/professionalsummary/604e53c9635db508b9216c35


###

POST http://localhost:5001/professionalsummary
Content-Type: application/json

{
    "cv": "604d6f3b4919d19f95f3200f",
    "description": "<p><strong>hoausdhasdasud</strong></p>"
}

###

GET http://localhost:5001/professionalsummary/cv/604d6f3b4919d19f95f3200f

###

GET http://localhost:5001/professionalsummary/604e53c9635db508b9216c35

###

POST http://localhost:5001/api/employment/6052c5c84f73323def3fff44/create
Content-Type: application/json

{
    
}